name: Create NEON DODGE Keystore
on:
  workflow_dispatch:
jobs:
  create-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Create keystore
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          keytool -genkeypair \
            -v \
            -keystore neondodge-release.keystore \
            -alias "$KEY_ALIAS" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            -dname "CN=NEON DODGE, OU=Elevoid, O=Elevoid, L=Almaty, ST=Almaty, C=KZ"
      - name: Encode keystore
        run: |
          base64 -w 0 neondodge-release.keystore > neondodge-release.keystore.base64
      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: NEON-DODGE-KEYSTORE
          path: |
            neondodge-release.keystore
            neondodge-release.keystore.base64